# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_language',
            field=models.CharField(max_length=5, null=True, verbose_name='current language'),
        ),
    ]
