# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_profile_current_language'),
        ('organization', '0017_profile_is_foundation_manager'),
    ]

    operations = [
    ]
