# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_membership_is_treasurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='onscreen_checkout',
            field=models.BooleanField(default=True, verbose_name='on-screen checkout'),
        ),
    ]
