# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_membership_onscreen_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
    ]
