# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20160419_1133'),
        ('billing', '0016_merge'),
    ]

    operations = [
    ]
