# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is available?'),
        )
    ]
