# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_merge'),
        ('scheduling', '0012_auto_20161208_1426'),
    ]

    operations = [
    ]
