# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_auto_20180702_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(choices=[('enrollopen', 'Enrollment open'), ('enrollclosed', 'Enrollment closed'), ('reminder', 'Reminder'), ('enrolllapsed', 'Enrollment period lapsed')], max_length=32, verbose_name='name'),
        ),
    ]
